metadata:
  name: book-review-backend
  namespace: book-review
spec:
  type: ClusterIP  # internal only
  selector:
    app: book-review-backend
  ports:
    - protocol: TCP
      port: 3001       # port that frontend calls
      targetPort: 3001 # container port
