apiVersion: v1
kind: Service
metadata:
  name: book-review-frontend
  namespace: book-review
spec:
  type: ClusterIP
  selector:
    app: book-review-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
